# Generated by Django 4.2 on 2023-04-18 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_website", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftcardvalue",
            name="name",
        ),
        migrations.AddField(
            model_name="giftcardvalue",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main_website.giftcardregion",
            ),
        ),
        migrations.RemoveField(
            model_name="giftcard",
            name="region",
        ),
        migrations.RemoveField(
            model_name="giftcard",
            name="type",
        ),
        migrations.RemoveField(
            model_name="giftcard",
            name="value",
        ),
        migrations.AddField(
            model_name="giftcard",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main_website.giftcardregion",
            ),
        ),
        migrations.AddField(
            model_name="giftcard",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main_website.giftcardtype",
            ),
        ),
        migrations.AddField(
            model_name="giftcard",
            name="value",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main_website.giftcardvalue",
            ),
        ),
    ]
