# Generated by Django 4.2 on 2023-04-18 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "main_website",
            "0002_remove_giftcardvalue_name_giftcardvalue_region_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftcardvalue",
            name="region",
        ),
    ]
