# Generated by Django 4.2 on 2023-04-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_website", "0003_remove_giftcardvalue_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcard",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
