# Generated by Django 4.2 on 2023-04-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_website", "0005_giftcardregion_currency_symbol_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftcardregion",
            name="currency_symbol",
        ),
        migrations.AddField(
            model_name="giftcardregion",
            name="currency",
            field=models.CharField(default="€", max_length=6),
        ),
    ]
