# Generated by Django 4.2 on 2023-04-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_website", "0006_remove_giftcardregion_currency_symbol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcardregion",
            name="currency",
            field=models.CharField(default="EURO", max_length=6),
        ),
    ]
