# Generated by Django 4.2 on 2023-04-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_website", "0007_alter_giftcardregion_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=50)),
                ("message", models.TextField()),
            ],
        ),
    ]
