# Generated by Django 4.2 on 2023-05-04 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_website", "0008_contactmessages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="giftcardvalue",
            options={"ordering": ["value"]},
        ),
    ]
