# Generated by Django 4.2 on 2023-05-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_website", "0011_shippingcost_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingcost",
            name="active",
            field=models.BooleanField(
                default=False,
                help_text="If you activate this shipping, an other shipping method will be deactivated!",
            ),
        ),
        migrations.AlterField(
            model_name="shippingcost",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
    ]
