# Generated by Django 4.2 on 2023-05-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_website", "0012_alter_shippingcost_active_alter_shippingcost_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftcardCodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="0000-0000-0000", max_length=14)),
                (
                    "giftcard",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main_website.giftcard",
                    ),
                ),
            ],
        ),
    ]
