# Generated by Django 4.2 on 2023-05-10 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_website", "0013_giftcardcodes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactMessages",
            new_name="ContactMessage",
        ),
        migrations.RenameModel(
            old_name="GiftcardCodes",
            new_name="GiftcardCode",
        ),
    ]
