# Generated by Django 4.2 on 2023-05-10 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_website", "0015_giftcardcode_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="giftcardcode",
            old_name="status",
            new_name="for_sale",
        ),
    ]
