# Generated by Django 4.2 on 2023-05-17 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("main_website", "0016_rename_status_giftcardcode_for_sale"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("transaction_id", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("item_list", models.ManyToManyField(to="main_website.giftcard")),
            ],
        ),
    ]
