# Generated by Django 4.2 on 2023-05-17 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("main_website", "0017_digitalorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitalorder",
            name="order_number",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
