# Generated by Django 4.2 on 2023-05-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_website", "0018_alter_digitalorder_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="digitalorder",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="digitalorder",
            name="payment_method",
            field=models.CharField(default="asd", max_length=50),
            preserve_default=False,
        ),
    ]
