# Generated by Django 4.2 on 2023-05-17 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_website", "0019_remove_digitalorder_transaction_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftcard",
            name="available_stock",
        ),
    ]
