# Generated by Django 4.2 on 2023-05-17 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main_website", "0020_remove_giftcard_available_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalorder",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
