# Generated by Django 4.2 on 2023-05-17 14:32

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("main_website", "0021_digitalorder_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderWithShipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("payment_method", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("county", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("item_list", models.ManyToManyField(to="main_website.giftcard")),
            ],
        ),
    ]
